version: "3"
    
services:
  mysql_daten:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
#      MYSQL_DATABASE: wordpress
#      MYSQL_USER: wordpress
#      MYSQL_PASSWORD: wordpress
    volumes:
      - ./mysql_daten:/var/lib/mysql
    ports:
      - 3306:3306

volumes:
  mysql_daten:
