version: '3'

services:
  pg_daten:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=postgres
      - POSTGRES_DB=stage
    volumes:
      - ./pg_daten:/var/lib/postgresql/data
    ports:
      - "5432:5432"
