Vagrant.configure("2") do |config|
    config.vm.box = "bento/ubuntu-20.04"
#    config.vm.network "public_network", ip: "192.168.13.113"
#    config.vm.network "private_network", ip xxx.xxx.xxx.xxx
#    config.vm.network "private_network", type: "dhcp"
#
# Vagrant Monitoring. Node_exporter/Prometheus/Grafana
#    config.vm.network  "forwarded_port", guest: 9090, host: 9190, auto_correct: true
#    config.vm.network  "forwarded_port", guest: 9100, host: 9200, auto_correct: true
#    config.vm.network  "forwarded_port", guest: 9093, host: 9193, auto_correct: true
#    config.vm.network  "forwarded_port", guest: 9094, host: 9194, auto_correct: true
#    config.vm.network  "forwarded_port", guest: 3000, host: 3100, auto_correct: true
#
#    config.vm.network  "forwarded_port", guest: 19999, host: 29999, auto_correct: true
#
# Docker-Compose Postgres. 2 volumes. dz_6_2
    config.vm.network  "forwarded_port", guest: 5432, host: 15432, auto_correct: true
#    config.vm.network  "forwarded_port", guest: 5433, host: 15433, auto_correct: true
#
# Docker-Compose MySQL. 1 volumes. dz_6_3
    config.vm.network  "forwarded_port", guest: 3306, host: 13306, auto_correct: true
#
#
    config.vm.hostname = "vm-vagrant"
    config.vm.box_check_update = false

    config.vm.provider "virtualbox" do |v|
        v.name = "vm-learn"
        v.memory = 2048
        v.cpus = 2
        v.gui = false
    end
end
