version: '3'

services:
  pg_daten:
    image: postgres:12
    restart: always
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=postgres
      - POSTGRES_DB=stage
    volumes:
      - ./pg_daten:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pg_backup:
    image: postgres:12
    restart: always
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=postgres
      - POSTGRES_DB=stage
    volumes:
      - ./pg_backup:/var/lib/postgresql/data
    ports:
      - "5433:5433"

